Saving and updating cgh, hpos and indic
Ferlab-Ste-Justine/clin-frontend pull request #276
Opened 2020-09-04 01:00 UTC by FrancisRenaud

This does not include adding or deleting hpos yet.

2020-09-04 12:02 UTC, YanLabCHU requested changes
Some more comments:

- remove `hpo_terms.json` if it's not used

- Don't delete `pnpm-lock.yaml` from the repository

2020-09-08 18:12 UTC, FrancisRenaud commented on client/src/components/screens/PatientSubmission/ClinicalInformation.jsx
> +  cghInterpretation,
First 3 are used. Last one has been removed in cleanup.

2020-09-09 12:39 UTC, YanLabCHU commented on client/src/components/screens/PatientSubmission/ClinicalInformation.jsx
> +  cghInterpretation,
Yeah, I was talking about that one, Github shows 4 lines for some reason lol

2020-09-09 12:47 UTC, YanLabCHU requested changes
Like said before: 
- Remove `hpo_terms.json` if it's not used
- Don't delete `pnpm-lock.yaml` from the repository

2020-09-23 07:42 UTC, closed without merging

2020-09-23 07:42 UTC, FrancisRenaud commented
This PR is now obsolete