fix: #525 translate hardcoded labels
Ferlab-Ste-Justine/clin-frontend pull request #398
Opened 2020-12-07 20:05 UTC by francisprovost

2020-12-08 13:28 UTC, YanLabCHU requested changes
En plus des commentaires que j'ai mis, il manque certaines translations dans le fichier `en.js`

2020-12-08 13:28 UTC, YanLabCHU commented on client/src/locales/en.js
> +  'screen.patient.details.completeForm': 'Complete the Form',
`Fill out the form`

2020-12-08 13:28 UTC, YanLabCHU commented on client/src/locales/en.js
> +  'screen.patient.details.noInfoAvailable': 'No Clinical information available',
`No clinical information available`

2020-12-08 13:28 UTC, YanLabCHU commented on client/src/locales/en.js
> +  'screen.patient.details.diagnosticHypothesis': 'Diagnostic Hypothesis',
```
  'screen.patient.details.investigationSummary': 'Investigation summary',
  'screen.patient.details.consultationSummary': 'Consultation summary',
  'screen.patient.details.diagnosticHypothesis': 'Diagnostic hypothesis',
```

2020-12-08 13:28 UTC, YanLabCHU commented on client/src/locales/en.js
> +  'screen.patientvariant.navigation.importList': 'Import a List',
`Import list`

2020-12-08 13:28 UTC, YanLabCHU commented on client/src/locales/en.js
> +  'screen.variantDetails.summaryTab.emptyTable': 'No Data Available',
`No data Available`

2020-12-08 13:28 UTC, YanLabCHU commented on client/src/locales/en.js
> +  'form.patientSubmission.form.title': 'New patient and genomic test order',
`New patient and genomic test prescription`

2020-12-08 13:28 UTC, YanLabCHU commented on client/src/locales/en.js
> +  'form.patientSubmission.form.validation.practioner': 'Please specify the name of the practioner',
`Please specify the name of the referring practitioner`

2020-12-08 13:28 UTC, YanLabCHU commented on client/src/locales/en.js
> +  'form.patientSubmission.form.section.consent': 'Consentements',
`Consents`

2020-12-08 13:28 UTC, YanLabCHU commented on client/src/locales/en.js
> +  'form.patientSubmission.clinicalInformation.delete': 'Supprimer',
`Delete`

2020-12-08 13:28 UTC, YanLabCHU commented on client/src/locales/en.js
> +  'form.patientSubmission.clinicalInformation.title': 'Informations Cliniques',
`Clinical Information`

2020-12-08 13:28 UTC, YanLabCHU commented on client/src/locales/en.js
> +  'form.patientSubmission.clinicalInformation.analysisType': 'Type d’analyse',
`Analysis type`

2020-12-08 13:28 UTC, YanLabCHU commented on client/src/locales/en.js
> +  'form.patientSubmission.clinicalInformation.investigationSummary': 'Résumé de l’investigation',
`Investigation summary`

2020-12-08 13:28 UTC, YanLabCHU commented on client/src/locales/en.js
> +  'form.patientSubmission.clinicalInformation.precision': 'Précision',
`Precision`

2020-12-08 13:28 UTC, YanLabCHU commented on client/src/locales/en.js
> +  'form.patientSubmission.clinicalInformation.targetedSequencing': 'Séquençage ciblé',
`Targeted sequencing`

2020-12-08 13:28 UTC, YanLabCHU commented on client/src/locales/en.js
> +  'form.patientSubmission.clinicalInformation.pleaseSpecify': 'Veuillez préciser...',
`Please specify...`

2020-12-08 13:28 UTC, YanLabCHU commented on client/src/locales/en.js
> +  'form.patientSubmission.clinicalInformation.summary': 'Résumé',
`Summary`

2020-12-08 13:28 UTC, YanLabCHU commented on client/src/locales/en.js
> +  'form.patientSubmission.clinicalInformation.optional': 'Facultatif',
`Optional`

2020-12-08 13:28 UTC, YanLabCHU commented on client/src/locales/en.js
> +  'form.patientSubmission.clinicalInformation.searchClinicalSign': 'Chercher un signe clinique...',
`Search for a clinical sign...`

2020-12-08 13:28 UTC, YanLabCHU commented on client/src/locales/en.js
> +  'form.patientSubmission.form.practioner': 'Practioner',
`'form.patientSubmission.form.practitioner': 'Practitioner'`

2020-12-08 17:17 UTC, francisprovost commented on client/src/locales/en.js
> +  'screen.patient.details.cancel': 'CAncael',
Jpense que je me suis enfargé dans mon clavier lol

2020-12-09 12:13 UTC, YanLabCHU requested changes

2020-12-09 12:13 UTC, YanLabCHU commented on client/src/locales/en.js
> +  'form.patientSubmission.clinicalInformation.validation.clinicalSign': 'Choisissez au moins un signe clinique depuis l’arbre de gauche afin de fournir l’information la plus complète possible sur le
J'aurais dû être plus précis, c'est de ça dont je parlais quand j'ai dit qu'il manquait des traductions

2020-12-09 15:27 UTC, YanLabCHU approved these changes

2020-12-09 15:37 UTC, merged