Feat/new res creation workflow
Ferlab-Ste-Justine/clin-frontend pull request #444
Opened 2021-01-26 18:50 UTC by YanLabCHU

2021-01-26 18:50 UTC, YanLabCHU commented
Depends on https://github.com/Ferlab-Ste-Justine/clin-fhir-server/pull/31

2021-01-26 19:54 UTC, francisprovost requested changes
Quelques petits détails

2021-01-26 19:54 UTC, francisprovost commented on client/src/components/screens/PatientCreation/components/FormModal/index.tsx
> +              actions.createPatient(newPatient, group);
Il manque pas le fetus vs person en quelques part ici?

2021-01-26 19:54 UTC, francisprovost commented on client/src/components/screens/PatientCreation/components/FormModal/index.tsx
> +                .withBirthDate(new Date(values.birthday.toDate()))
La date est optionel quand c'est un fetus

2021-01-26 19:54 UTC, francisprovost commented on client/src/components/screens/PatientSearch/index.jsx
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
À retirer

2021-01-26 19:54 UTC, francisprovost commented on client/src/components/screens/PatientSearch/index.jsx
> +              </Button> */ }
On peut probablement retirer le vieux bouton

2021-01-26 19:54 UTC, francisprovost commented on client/src/helpers/fhir/api/CreatePatient.ts
> +  const memebers = get(bundle, 'entry[1].resource.member', []);
ptite typo `memebers`

2021-01-27 10:44 UTC, YanLabCHU commented on client/src/components/screens/PatientCreation/components/FormModal/index.tsx
> +              actions.createPatient(newPatient, group);
Le foetus ça viendra plus tard, il y a des changement dans le guide à faire

2021-01-27 15:01 UTC, francisprovost approved these changes

2021-01-27 15:39 UTC, merged