refactoring code
Ferlab-Ste-Justine/clin-frontend pull request #672
Opened 2021-05-12 16:59 UTC by claudia1296

2021-05-12 18:41 UTC, francisprovost requested changes
Good job!! 👍   Quelques petits détails mais rien de gros

2021-05-12 18:41 UTC, francisprovost commented on client/src/components/screens/PatientSearch/components/PatientTable.tsx
> +searchProps: any
Il semble te manquer un tab sur ces props là. Ton eslint est setuper?

2021-05-12 18:41 UTC, francisprovost commented on client/src/components/screens/PatientSearch/components/PatientTable.tsx
> +  const handleGoToPatientScreen:any = (patientId: any, requestId: any) => {
`string` au lieu des `any`

2021-05-12 18:41 UTC, francisprovost commented on client/src/components/screens/PatientSearch/components/PatientTable.tsx
> +          value[key] = '--';
Les ts-ignore sont nécessaire? Si oui, peut-être ajouter un petit commentaire du pourquoi il est nécessaire

2021-05-12 18:41 UTC, francisprovost commented on client/src/components/screens/PatientSearch/components/PrescriptionHeader.tsx
> +  }
même chose mais là trop de tab 😂

2021-05-12 18:41 UTC, francisprovost commented on client/src/components/screens/PatientSearch/components/PrescriptionTable.tsx
> +}
Elles semblent pas mal similaire entre les deux tables. Tu pourrais peut-être les mettre en commun et utiliser `extends` s'il y en a de plus pour un vs l'autre

2021-05-12 18:41 UTC, francisprovost commented on client/src/components/screens/PatientSearch/components/PrescriptionTable.tsx
> +  const output:any = [];
Si t'as pas les détails de `output` tu pourrais mettre `any[]` comme ça t'as au au moins les fonctions d'un array quand tu l'utilise

2021-05-13 12:12 UTC, YanLabCHU reviewed
Great work!

2021-05-13 12:12 UTC, YanLabCHU commented on client/src/components/screens/PatientSearch/components/PrescriptionTable.tsx
> +  page:number
T'as oublié un espace après le `:`

2021-05-13 12:12 UTC, YanLabCHU commented on client/src/components/screens/PatientSearch/components/PrescriptionTable.tsx
> +    results.forEach((result: any) => {
Le type de `result` est `PrescriptionData` que tu peux importer [d'ici](https://github.com/Ferlab-Ste-Justine/clin-frontend/blob/master/client/src/helpers/search/types.ts#L1)

2021-05-13 12:12 UTC, YanLabCHU commented on client/src/components/screens/PatientSearch/components/PrescriptionTable.tsx
> +      const value = {
Même chose que dans `PatientTable`, change ça à `value: any = {` pis tu peux enlever les `@ts-ignore` en bas.

2021-05-13 12:12 UTC, YanLabCHU commented on client/src/components/screens/PatientSearch/components/PrescriptionTable.tsx
> +          // @ts-ignore
Même chose, avec le changement du commentaire en haut, tu peux enlever les `@ts-ignore`

2021-05-13 12:12 UTC, YanLabCHU commented on client/src/components/screens/PatientSearch/components/PrescriptionTable.tsx
> +        bloodRelationship: result.bloodRelationship,
Cette variable est une boolean, pis on la render directement [ici](https://github.com/Ferlab-Ste-Justine/clin-frontend/pull/672/files?file-filters%5B%5D=.jsx&file-filters%5B%5D=.tsx#diff-aebaec7289ae14f5194ed6041fbea48c3ce533d6863fc402fbb65661b55fcac2R257). l'application va crasher car elle s'attend à un `string`. Fak tu peux changer la valeur à `oui`, `non` ou `--`

2021-05-14 14:59 UTC, YanLabCHU approved these changes
Good job 👍🏻

2021-05-14 15:02 UTC, francisprovost approved these changes
🎉

2021-05-14 15:03 UTC, merged