fix: #233 feedback from qa
Ferlab-Ste-Justine/clin-frontend pull request #765
Opened 2021-09-24 15:12 UTC by evans-g-crsj

# [FIX] [Fetus display in profile card]

closes #[233]

## Description
fixes feedback from qa 

Critères de succès
should clearly show when patient is fetus or mother of fetus
## Validation

- [ ] Test Coverage
- [ ] QA Done
- [ ] Design/UI Approved from design

## Screenshot
![image](https://user-images.githubusercontent.com/54366437/134698585-67ddbcbb-6644-4f6c-bcdf-fcd972ccae1a.png)

## QA
check a patient who is a fetus or a mother of of fetus

note: when a mother of a fetus parent should be displayed instead of fetus in the profile avatar. However, I let it as-is because it's most probably a backend problem and I do not want to hide it.

2021-09-24 15:29 UTC, francisl requested changes
Peux-tu ajouter 3 tests pour les 3 nouveau fichier?

2021-09-24 15:29 UTC, francisl commented on client/src/components/screens/Patient/components/FamilyTab/components/FamilyTable.tsx
> +  members.slice().sort((a, b) => +b.isProband - +a.isProband);
sais-tu a quoi sert le +(valuer) - +(valeur).

semble que mes math élémentaire sont confuse sur l'utilité

2021-09-24 18:50 UTC, evans-g-crsj commented on client/src/components/screens/Patient/components/FamilyTab/components/FamilyTable.tsx
> +  members.slice().sort((a, b) => +b.isProband - +a.isProband);
simplement à caster un booléen en valeur numérique vrai ou faux.

2021-09-27 13:36 UTC, francisl approved these changes
:shipit:

2021-09-27 13:37 UTC, francisl requested changes
juste le repertoire de tests

2021-09-27 13:37 UTC, francisl commented on client/src/components/screens/Patient/components/PatientDetails/profileCard.spec.tsx
> +
mettre le fichier dans un ./tests/

2021-09-28 18:29 UTC, francisl approved these changes
:shipit:

2021-09-28 18:30 UTC, merged