Clin-135 changer test dans prescription
Ferlab-Ste-Justine/clin-frontend pull request #779
Opened 2021-10-07 15:03 UTC by claudia1296

# changer test dans prescription

Clin-135

2021-10-07 15:54 UTC, francisl requested changes

2021-10-07 15:54 UTC, francisl commented on client/src/__tests__/PrescriptionCreation/index.spec.tsx
> +      const prescriptionTestLabel = screen.getByText("Maladies musculaires (Panel global)");
importe le fichier de traduction et tulise a partir de la clé. Comme ca, si il y a des changement dans le future, ton test ne va pas planter pour rien

2021-10-07 20:10 UTC, evans-g-crsj commented on client/src/helpers/fhir/types.ts
> +export enum analysisTest {
Lettre majuscule

2021-10-07 20:12 UTC, evans-g-crsj commented on client/src/helpers/fhir/fhir.js
> +    case 'PG':
non, il faut faire qq chose du genre: `case AnalysisTest.MY_ENUM_KEY`

2021-10-07 20:12 UTC, evans-g-crsj commented on client/src/helpers/fhir/fhir.js
> +    case 'PG':
non, il faut faire qq chose du genre: AnalysisTest.MY_ENUM_KEY

2021-10-07 20:17 UTC, evans-g-crsj commented on client/src/helpers/fhir/types.ts
> +export enum analysisTest {
tu peux faire: 

enum MyEnum {
PG = 'PG'
}

pour les codes. Ensuite, un record pour le texte:

codesMachinToDisplayText = {
[MyEnum.PG]: 'displaytext'
}

2021-10-07 20:20 UTC, evans-g-crsj commented on client/src/components/screens/PatientSubmission/components/ClinicalInformation/index.jsx
> +    for (let testName in analysisTest) {
Cette boucle, me semble inutile. Il faut revoir ton enum et batir un dictionnaire. Aussi, faire attention à faire le moins possible de manips dans un render.

2021-10-07 20:22 UTC, evans-g-crsj commented on client/src/helpers/fhir/fhir.js
> +    case 'PG':
je pense que display n'est approprié. Je mettrai plustot intlKey

2021-10-07 20:23 UTC, evans-g-crsj commented on client/src/components/screens/PatientSubmission/components/ClinicalInformation/index.jsx
> +                  >{ intl.get(`form.patientSubmission.clinicalInformation.analysis.options.${option.display}`) }
quand tous des types seront corrigés, tu feras qq chose du genre. int.get(analysisCode.intlKey)

2021-10-13 22:12 UTC, evans-g-crsj requested changes

2021-10-13 22:12 UTC, evans-g-crsj commented on client/src/components/screens/Patient/components/PrescriptionsTab/components/Prescriptions.tsx
> +                    {console.log('prescription.test', prescription.test)}
remove console

2021-10-14 13:56 UTC, merged