clin-493 mettre dynamique la liste des analyses
Ferlab-Ste-Justine/clin-frontend pull request #850
Opened 2021-12-07 17:51 UTC by claudia1296

clin-493 mettre dynamique la liste des analyses

2021-12-07 18:24 UTC, oliviercperrier commented on client/src/components/screens/PatientSubmission/components/ClinicalInformation/index.jsx
> +  buildCheckBoxName = (concept) =>{
```suggestion
  buildCheckBoxName = (concept) =>{
    const { lang } = this.props;
    const designation = concept.designation.find( d => d.language === lang);
    return designation ? designation.value : concept.display;
  }
```

2021-12-08 16:05 UTC, francisl requested changes
small change

2021-12-08 16:05 UTC, francisl commented on client/src/reducers/serviceRequestCode.ts
> +import * as actions from '../actions/type';
`actions/type` et importer ce que tu veux specifiquement

`import { actions.SERVICE_REQUEST_CODE_REQUESTED, ... } from 'actions/type'`

2021-12-08 16:05 UTC, francisl commented on client/src/store/urls.ts
> +  RequestCode = 'http://fhir.cqgc.ferlab.bio/CodeSystem/service-request-code',
Je crois pas qu'on devrait hardcover les protocols.

2021-12-08 16:05 UTC, evans-g-crsj submitted a review, later dismissed

2021-12-08 16:49 UTC, francisl approved these changes
:shipit:

2021-12-08 16:50 UTC, merged